[package]
name = "solana_beanie"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "solana_beanie"

[features]
default = []
anchor-debug = []
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]


[dependencies]
anchor-spl = { version = "0.31.1", default-features = false, features = [
    "associated_token",
    "token",
    "token_2022",
] }
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }
